variables:
  - &dockerfile Dockerfile
  - &repo codeberg.org/${CI_REPO_OWNER}/open-dronelog

when:
  branch: ${CI_REPO_DEFAULT_BRANCH}
  event: [push, tag, release, manual]

steps:
  publish-testing:
    image: codeberg.org/woodpecker-plugins/docker-buildx:6.0.3
    when:
      - event: [push, manual]
    settings:
      dockerfile: *dockerfile
      platforms: linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: testing
      username: ${CI_REPO_OWNER}
      password:
        from_secret: codeberg_token
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password

  publish-testing-nightly:
    image: codeberg.org/woodpecker-plugins/docker-buildx:6.0.3
    when:
      - event: tag
        evaluate: 'CI_COMMIT_TAG == "nightly"'
    settings:
      dockerfile: *dockerfile
      platforms: linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: testing
      username: ${CI_REPO_OWNER}
      password:
        from_secret: codeberg_token
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password

  publish-latest:
    image: codeberg.org/woodpecker-plugins/docker-buildx:6.0.3
    when:
      - event: [tag, release]
        evaluate: 'CI_COMMIT_TAG != "nightly"'
    settings:
      dockerfile: *dockerfile
      platforms: linux/amd64
      repo: *repo
      registry: codeberg.org
      tags: latest
      auto_tag: true
      username: ${CI_REPO_OWNER}
      password:
        from_secret: codeberg_token
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
