[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]
all-features = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"

# leaving this here for reference. Https links please.
allow-git = [
    # "https://github.com/chemicstry/wasm_thread",
]

[advisories]
ignore = [
    { id = "RUSTSEC-2023-0071", reason = "AFAICT exploiting this would require the attacker to be able to control the OIDC provider / set the OIDC provider, at which point several other layers of security already failed." },
    { id = "RUSTSEC-2026-0192", reason = "That dependency only comes in via buildtime usvg usage" },
    { id = "RUSTSEC-2026-0206", reason = "That dependency only comes in via buildtime usvg usage" },
]

[bans]
# Is a duplicate of rustc::multiple_crate_versions
multiple-versions = "warn"

skip-tree = [
    { crate = "windows-sys:<0.61.2", depth = 3, reason = "several crates use outdated versions" },
]

# https://embarkstudios.github.io/cargo-deny/checks/bans/cfg.html#the-workspace-dependencies-field-optional
[bans.workspace-dependencies]
# Determines what happens when more than 1 direct workspace dependency is resolved to the same crate and 1 or more declarations do not use workspace = true
duplicates = 'deny'
include-path-dependencies = true
# Determines what happens when a dependency in [workspace.dependencies] is not used in the workspace.
unused = 'deny'

[[bans.deny]]
name = "ring"
use-instead = "aws-lc-rs"
wrappers = [
    # cargo-about is a build-dependency that pulls in `ring`.
    "cargo-about",
    # come in via indirect dependency of cargo-about
    "rustls", "rustls-webpki"
]

[[bans.deny]]
name = "openssl"
use-instead = "aws-lc-rs"

# Blacklist multiple crate versions ---------------------
# deny-multiple-versions makes bans essentially a blacklist for multiple versions of the crate
# instead of blacklisting the crate in general.
#
# We also warn on all multiple versions, but solving all of them, with the number of dependencies we have
# would be a huge  and only temporary effort, so we only deny multiple versions for crates where we have a good reason to.

# It seems syn just had a breaking 3.0 release, it'll take some time until the ecosystem has caught up.
# [[bans.deny]]
# name = "syn"
# deny-multiple-versions = true
# reason = "multiple versions of this increases build time significantly"

[[bans.deny]]
name = "proc-macro2"
deny-multiple-versions = true
reason = "multiple versions of this increases build time significantly"

[[bans.deny]]
name = "rustls"
deny-multiple-versions = true
reason = "multiple versions of this could lead to subtle bugs or unpredicted panics"

[[bans.deny]]
name = "tracing"
deny-multiple-versions = true
reason = "multiple versions of this could lead to subtle bugs or unpredicted panics"

[[bans.deny]]
name = "tokio"
deny-multiple-versions = true
reason = "multiple versions of this could lead to subtle bugs or unpredicted panics"

#\ ---------------------

# Ban build scripts.
# Note that this has issues, as listed in the cargo deny book, and doesnt get checked befofe execution, so its certainly not perfect.
[bans.build]
# comments describe findings of a cursory scan on 20.05.26
allow-build-scripts = [
    # damned system crates
    "windows_aarch64_msvc", "windows_x86_64_msvc", "windows_aarch64_gnu", "windows_x86_64_gnu",
    # clib bindings
    "libc", "libm",
    # system headers
    "getrandom",
    # TODO: remove once they released the current main branches without build.rs
    "cookie@<=0.18.1", "httparse@<=1.10.1",
    # uses crypto algos in C
    "rustls", "aws-lc-rs", "aws-lc-sys", "ring", "crc32fast", "curve25519-dalek",
    # build.rs in these crates does, mostly checks about the environment and rustc capabilities.
    "anyhow", "eyre", "thiserror",
    # seems to do some strange thing with placing a module in a patch specific path
    "miniserde",
    # seems to set up some cfg macro aliases, and add some custom cfg values
    "nix",
    # -sys wraps zstd, -safe does: `Force the `std` feature in some cases`
    "zstd-safe", "zstd-sys",
    # seems to have a large build.rs that just sets up some cfg flags.
    "zerocopy",
    # sets rustc-check-cfg based on rustc version, hides private module
    "serde", "serde_core",
    # sets up the rustc version "cfg" macros (rustc-check-cfg)
    "rustversion",
    # makes sure that there is only one version of itself
    "rayon-core",
    # just does rustc-check-cfg
    "quote", "proc-macro2",
    # add respectively cfg(tsan_enabled), cfg(nightly), cfg(crossbeam_no_atomic,crossbeam_sanitize_thread,crossbeam_atomic_cell_force_fallback)
    "parking_lot_core", "slotmap", "crossbeam-utils",
    "camino", "icu_normalizer_data", "icu_properties_data", "zmij",
    "fs-err", "generic-array",
    # needs to bind to sqlite headers
    "libsqlite3-sys",
    "serde_json", "num-traits", "num-bigint-dig",
    "crossbeam-deque", "crossbeam-epoch", "inotify-sys",
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "GPL-2.0-only",
    "ISC",
    "MIT",
    "Unicode-3.0",
    "Zlib",
]
